### ISSUE TITLE
KeyError in Queue.py

### ISSUE THREAD

**Issue by mutepigz** [tijme/not-your-average-web-crawler#5]
when i try to scan my blog , here is a Error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/mutepig/workplace/spider/nyawc/CrawlerThread.py", line 116, in run
    self.__callback(self.__queue_item, new_requests, failed)
  File "/Users/mutepig/workplace/spider/nyawc/Crawler.py", line 247, in __request_finish
    self.__spawn_new_requests()
  File "/Users/mutepig/workplace/spider/nyawc/Crawler.py", line 104, in __spawn_new_requests
    if self.__spawn_new_request():
  File "/Users/mutepig/workplace/spider/nyawc/Crawler.py", line 124, in __spawn_new_request
    self.__request_start(first_in_line)
  File "/Users/mutepig/workplace/spider/nyawc/Crawler.py", line 208, in __request_start
    self.queue.move(queue_item, QueueItem.STATUS_IN_PROGRESS)
  File "/Users/mutepig/workplace/spider/nyawc/Queue.py", line 130, in move
    del items[queue_item.get_hash()]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 85, in __delitem__
    dict_delitem(self, key)
KeyError: "gethttpmutepigclub/index.php/start-page.htmlOrderedDict([('replyTo', '3')])"
```
I debuged it for a time, and i found a possible reason for it. two requests in the queue : 
```
gethttpmutepigclub/index.php/start-page.htmlOrderedDict([(u'replyTo', u'3')]
gethttpmutepigclub/index.php/start-page.htmlOrderedDict([('replyTo', '3')])
```
the two same requests have diffrent hash , it's strange, but i don't know why.
so i use a brute way to solve it : unicode every string in `query_string_to_dict`
```
295         for key_value in query.split("&"):                                                                                                                                       
296             key_value_pair = key_value.split("=", 1)                                                                                                                             
297                                                                                                                                                                                  
298             key = key_value_pair[0] if len(key_value_pair) >= 1 else ""                                                                                                          
299             value = key_value_pair[1] if len(key_value_pair) == 2 else ""                                                                                                        
300             key = unicode(key)    # add                                                                                                                                               
301             value = unicode(value)   # add                                                                                                                                            
302                                                                                                                                                                                  
303             query_params[key] = value   
```
it works , but maybe here is a better way to solve it.

**Comment by tijme** [comment]
@mutepigz Thanks for the report and the debugging. This seems to be a Python 2 only bug. I'm going to check and see if I can implement a good fix for this issue.

**Comment by tijme** [comment]
@mutepigz I just fixed this issue on the master branch. Somehow, when crawling your website, Python's requests module returned a unicode URL instead of a string URL. This was causing issues when generating the hash.

38ecc2832ac285ac3481ec828b266b7e54efeac1
ec8571a8f459a982b17d5d15fa3964faa2106e36
4e9e22fd6097326929ff546a0c05831aa47a3589
92bd385cdf33be46ecbb91cc01d0565ced48a46a
e4ceb76637151a8ebe7437e2404a8faaf1558754

`pip install --upgrade --force-reinstall git+https://github.com/tijme/not-your-average-web-crawler.git`
